import os

SERVICE_ID = os.getenv("FASTLY_SERVICE_ID")
GDN_URL = os.getenv("GDN_URL")
GDN_USERNAME = os.getenv("GDN_USERNAME")
GDN_PASSWORD = os.getenv("GDN_PASSWORD")
COLLECTION_NAME = os.getenv("LOGS_COLLECTION_NAME")
